CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    login VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    permission VARCHAR(10) NOT NULL CHECK (permission IN ('ADMIN', 'MANAGER', 'USER'))
);